# Generated by Django 5.0.1 on 2024-01-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_is_active_partner_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name_company',), 'permissions': [('can_blocked', 'can_blocked')], 'verbose_name': 'партнер', 'verbose_name_plural': 'партнер'},
        ),
    ]
